import * as constant from './constants';

const items = {
  0: {
    wikiLink: "https://riskofrain2.fandom.com/wiki/Soldier%27s_Syringe",
    name: "Soldier's Syringe",
    image: "https://vignette.wikia.nocookie.net/riskofrain2/images/f/f2/Soldier%27s_Syringe.png/revision/latest?cb=20190411035100",
    shortDescription: "Increases attack speed.",
    description: "Increases attack speed by 15% (+15% per stack).",
    rarity: constant.ItemRarity.COMMON,
    category: [
      constant.Category.DAMAGE,
    ],
    unlock: {
      name: "Advancement",
      description: "The achievement is obtained by completing a Teleporter Event.",
      link: "https://riskofrain2.fandom.com/wiki/Advancement",
    },
    id: 0,
    stats: [{
      stat: constant.StatType.ATTACK_SPEED,
      value: "15%",
      stackType: constant.StackType.LINEAR,
      stackValue: "+15%", 
    }],
  },
  1: {
    wikiLink: "https://riskofrain2.fandom.com/wiki/Tougher_Times",
    name: "Tougher Times",
    image: "https://vignette.wikia.nocookie.net/riskofrain2/images/3/39/Tougher_Times.png/revision/latest?cb=20190411035134",
    shortDescription: "Chance to block incoming damage.",
    description: "15% (+15% per stack) chance to block incoming damage. Unaffected by luck.",
    rarity: constant.ItemRarity.COMMON,
    category: [
      constant.Category.UTILITY,
    ],
    unlock: {
      name: "Learning Process",
      description: "The achievement is obtained by dying 5 times.",
      link: "https://riskofrain2.fandom.com/wiki/Learning_Process",
    },
    id: 1,
    stats: [{
      stat: constant.StatType.CHANCE,
      value: "15%",
      stackType: constant.StackType.HYPERBOLIC,
      stackValue: "+15%", 
    }],
  },
  2: {
    wikiLink: "https://riskofrain2.fandom.com/wiki/Brilliant_Behemoth",
    name: "Brilliant Behemoth",
    image: "https://vignette.wikia.nocookie.net/riskofrain2/images/f/fa/Brilliant_Behemoth.png/revision/latest?cb=20190411034332",
    shortDescription: "All your attacks explode!",
    description: "All your attacks explode in a 4m (+2.5m per stack) radius for a bonus 60% TOTAL damage to nearby enemies.",
    rarity: constant.ItemRarity.LEGENDARY,
    category: [
      constant.Category.DAMAGE,
    ],
    id: 2,
    stats: [{
      stat: constant.StatType.RADIUS,
      value: "4m",
      stackType: constant.StackType.LINEAR,
      stackValue: "+2.5m", 
    }],
  },
  3: {
    wikiLink: "https://riskofrain2.fandom.com/wiki/AtG_Missile_Mk._1",
    name: "AtG Missile Mk. 1",
    image: "https://vignette.wikia.nocookie.net/riskofrain2/images/6/6a/AtG_Missile_Mk._1.png/revision/latest?cb=20190411034310",
    shortDescription: "Chance to fire a missile.",
    description: "10% chance to fire a missile that deals 300% (+300% per stack) TOTAL damage.",
    rarity: constant.ItemRarity.UNCOMMON,
    category: [
      constant.Category.DAMAGE,
    ],
    id: 3,
    stats: [{
      stat: constant.StatType.DAMAGE,
      value: "300%",
      stackType: constant.StackType.LINEAR,
      stackValue: "+300%", 
    }],
  },
  4: {
    wikiLink: "https://riskofrain2.fandom.com/wiki/Will-o%27-the-wisp",
    name: "Will-o'-the-wisp",
    image: "https://vignette.wikia.nocookie.net/riskofrain2/images/c/c4/Will-o%27-the-wisp.png/revision/latest?cb=20190411035214",
    shortDescription: "Detonate enemies on kill.",
    description: "On killing an enemy, spawn a lava pillar in a 12m (+2.4m per stack) radius for 350% (+280% per stack) base damage.",
    rarity: constant.ItemRarity.UNCOMMON,
    category: [
      constant.Category.DAMAGE,
      constant.Category.ON_KILL_EFFECT,
    ],
    id: 4,
    stats: [{
      stat: constant.StatType.DAMAGE,
      value: "350%",
      stackType: constant.StackType.LINEAR,
      stackValue: "+280%", 
    },
    {
      stat: constant.StatType.DAMAGE,
      value: "12m",
      stackType: constant.StackType.LINEAR,
      stackValue: "+2.4m", 
    }],
  },
  5: {
    wikiLink: "https://riskofrain2.fandom.com/wiki/Ceremonial_Dagger",
    name: "Ceremonial Dagger",
    image: "https://vignette.wikia.nocookie.net/riskofrain2/images/7/76/Ceremonial_Dagger.png/revision/latest?cb=20190411034354",
    shortDescription: "Killing an enemy releases homing daggers.",
    description: "Killing an enemy fires out 3 homing daggers that deal 150% (+150% per stack) base damage.",
    rarity: constant.ItemRarity.LEGENDARY,
    category: [
      constant.Category.DAMAGE,
      constant.Category.ON_KILL_EFFECT,
    ],
    id: 5,
    stats: [{
      stat: constant.StatType.DAMAGE,
      value: "150%",
      stackType: constant.StackType.LINEAR,
      stackValue: "+150%", 
    }],
  },
  6: {
    wikiLink: "https://riskofrain2.fandom.com/wiki/Monster_Tooth",
    name: "Monster Tooth",
    image: "https://vignette.wikia.nocookie.net/riskofrain2/images/3/3b/Monster_Tooth.png/revision/latest?cb=20190411034916",
    shortDescription: "Drop a healing orb on kill.",
    description: "Killing an enemy spawns a healing orb that heals for 8 (+8 per stack) health.",
    rarity: constant.ItemRarity.COMMON,
    category: [
      constant.Category.HEALING,
      constant.Category.ON_KILL_EFFECT,
    ],
    id: 6,
    stats: [{
      stat: constant.StatType.HEAL,
      value: "8",
      stackType: constant.StackType.LINEAR,
      stackValue: "+8", 
    }],
  },
  7: {
    wikiLink: "https://riskofrain2.fandom.com/wiki/Lens-Maker%27s_Glasses",
    name: "Lens-Maker's Glasses",
    image: "https://vignette.wikia.nocookie.net/riskofrain2/images/2/23/Lens-Maker%27s_Glasses.png/revision/latest?cb=20190411034902",
    shortDescription: "Chance to 'Critically Strike', dealing double damage.",
    description: "Your attacks have a 10% (+10% per stack) chance to 'Critically Strike', dealing double damage.",
    rarity: constant.ItemRarity.COMMON,
    category: [
      constant.Category.DAMAGE,
    ],
    id: 7,
    stats: [{
      stat: constant.StatType.CRITICAL_STRIKE_CHANCE,
      value: "10%",
      stackType: constant.StackType.LINEAR,
      stackValue: "+10%",
      effectiveMax: 10, 
    }],
  },
  8: {
    wikiLink: "https://riskofrain2.fandom.com/wiki/Paul%27s_Goat_Hoof",
    name: "Paul's Goat Hoof",
    image: "https://vignette.wikia.nocookie.net/riskofrain2/images/4/4a/Paul%27s_Goat_Hoof.png/revision/latest?cb=20190411034934",
    shortDescription: "Move faster.",
    description: "Increases movement speed by 14% (+14% per stack).",
    rarity: constant.ItemRarity.COMMON,
    category: [
      constant.Category.UTILITY,
    ],
    unlock: {
      name: "Is This Bugged",
      description: "The achievement is obtained by failing a shrine 3 times in a row.",
      link: "https://riskofrain2.fandom.com/wiki/%22Is_This_Bugged%3F%22",
    },
    id: 8,
    stats: [{
      stat: constant.StatType.MOVEMENT_SPEED,
      value: "14%",
      stackType: constant.StackType.LINEAR,
      stackValue: "+14%", 
    }],
  },
  9: {
    wikiLink: "https://riskofrain2.fandom.com/wiki/Hopoo_Feather",
    name: "Hopoo Feather",
    image: "https://vignette.wikia.nocookie.net/riskofrain2/images/3/3a/Hopoo_Feather.png/revision/latest?cb=20190411034827",
    shortDescription: "Gain an extra jump.",
    description: "Gain +1 (+1 per stack) maximum jump count.",
    rarity: constant.ItemRarity.UNCOMMON,
    category: [
      constant.Category.UTILITY,
      constant.Category.AI_BLACKLIST,
    ],
    id: 9,
    stats: [{
      stat: constant.StatType.EXTRA_JUMP,
      value: "1",
      stackType: constant.StackType.LINEAR,
      stackValue: "+1", 
    }],
  },
  11: {
    wikiLink: "https://riskofrain2.fandom.com/wiki/Ukulele",
    name: "Ukulele",
    image: "https://vignette.wikia.nocookie.net/riskofrain2/images/9/98/Ukulele.png/revision/latest?cb=20190411035149",
    shortDescription: "...and his music was electric.",
    description: "25% chance to fire chain lighting for 80% TOTAL damage on up to 3 (+2 per stack) targets within 20m (+2m per stack).",
    rarity: constant.ItemRarity.UNCOMMON,
    category: [
      constant.Category.DAMAGE,
    ],
    id: 11,
    stats: [{
      stat: constant.StatType.AMOUNT,
      value: "3",
      stackType: constant.StackType.LINEAR,
      stackValue: "+2",
      effectiveMax: 22, 
    },
    {
      stat: constant.StatType.RADIUS,
      value: "20m",
      stackType: constant.StackType.LINEAR,
      stackValue: "+2m", 
    }],
  },
  13: {
    wikiLink: "https://riskofrain2.fandom.com/wiki/Leeching_Seed",
    name: "Leeching Seed",
    image: "https://vignette.wikia.nocookie.net/riskofrain2/images/a/a0/Leeching_Seed.png/revision/latest?cb=20190411034843",
    shortDescription: "Dealing damage heals you.",
    description: "Dealing damage heals you for 1 (+1 per stack) health.",
    rarity: constant.ItemRarity.UNCOMMON,
    category: [
      constant.Category.HEALING,
    ],
    id: 13,
    stats: [{
      stat: constant.StatType.HEAL,
      value: "1",
      stackType: constant.StackType.LINEAR,
      stackValue: "+1", 
    }],
  },
  14: {
    wikiLink: "https://riskofrain2.fandom.com/wiki/Frost_Relic",
    name: "Frost Relic",
    image: "https://vignette.wikia.nocookie.net/riskofrain2/images/5/58/Frost_Relic.png/revision/latest?cb=20190411034739",
    shortDescription: "Killing enemies surrounds you with an ice storm.",
    description: "Killing an enemy surrounds you with an ice storm that deals 600% damage per second. The storm grows with every kill, increasing its radius by 1m. Stacks up to 6m (+6m per stack).",
    rarity: constant.ItemRarity.LEGENDARY,
    category: [
      constant.Category.DAMAGE,
      constant.Category.ON_KILL_EFFECT,
    ],
    id: 14,
    stats: [{
      stat: constant.StatType.RADIUS,
      value: "6m",
      stackType: constant.StackType.LINEAR,
      stackValue: "+6m", 
    }],
  },
  15: {
    wikiLink: "https://riskofrain2.fandom.com/wiki/Happiest_Mask",
    name: "Happiest Mask",
    image: "https://vignette.wikia.nocookie.net/riskofrain2/images/d/d4/Happiest_Mask.png/revision/latest?cb=20190411034807",
    shortDescription: "Chance on killing an enemy to summon a ghost.",
    description: "Killing enemies has a 7% chance to spawn a ghost of the killed enemy with 1500% damage. Lasts 30s (+30s per stack).",
    rarity: constant.ItemRarity.LEGENDARY,
    category: [
      constant.Category.DAMAGE,
      constant.Category.UTILITY,
      constant.Category.ON_KILL_EFFECT,
    ],
    id: 15,
    stats: [{
      stat: constant.StatType.DURATION,
      value: "30s",
      stackType: constant.StackType.LINEAR,
      stackValue: "+30s", 
    }],
  },
  16: {
    wikiLink: "https://riskofrain2.fandom.com/wiki/Bustling_Fungus",
    name: "Bustling Fungus",
    image: "https://vignette.wikia.nocookie.net/riskofrain2/images/3/33/Bustling_Fungus.png/revision/latest?cb=20190411034345",
    shortDescription: "Heal all nearby allies after standing still for 2 seconds.",
    description: "After standing still for 2 seconds, create a zone that heals for 4.5% (+2.25% per stack) of your health every second to all allies within 3m (+1.5m per stack).",
    rarity: constant.ItemRarity.COMMON,
    category: [
      constant.Category.HEALING,
      constant.Category.AI_BLACKLIST,
    ],
    id: 16,
    stats: [{
      stat: constant.StatType.HEALTH_REGENERATION,
      value: "4.5%/s",
      stackType: constant.StackType.LINEAR,
      stackValue: "+2.25%/s",
      effectiveMax: 44, 
    },
    {
      stat: constant.StatType.RADIUS,
      value: "3m",
      stackType: constant.StackType.LINEAR,
      stackValue: "+1.5m", 
    }],
  },
  17: {
    wikiLink: "https://riskofrain2.fandom.com/wiki/Crowbar",
    name: "Crowbar",
    image: "https://vignette.wikia.nocookie.net/riskofrain2/images/c/c0/Crowbar.png/revision/latest?cb=20190411034408",
    shortDescription: "Deal more damage to healthy enemies.",
    description: "Deal 150% (+50% per stack) damage to enemies above 90% health.",
    rarity: constant.ItemRarity.COMMON,
    category: [
      constant.Category.DAMAGE,
    ],
    unlock: {
      name: "The Basics",
      description: "The achievement is obtained by discovering 10 unique white items.",
      link: "https://riskofrain2.fandom.com/wiki/The_Basics",
    },
    id: 17,
    stats: [{
      stat: constant.StatType.DAMAGE,
      value: "150%",
      stackType: constant.StackType.LINEAR,
      stackValue: "+50%", 
    }],
  },
  19: {
    wikiLink: "https://riskofrain2.fandom.com/wiki/Predatory_Instincts",
    name: "Predatory Instincts",
    image: "https://vignette.wikia.nocookie.net/riskofrain2/images/3/39/Predatory_Instincts.png/revision/latest?cb=20190411034944",
    shortDescription: "'Critical Strikes' increase attack speed. Stacks 3 times.",
    description: "Gain 5% critical chance (+0% per stack). Critical strikes increase attack speed by 12%. Maximum cap of 36% (+24% per stack) attack speed.",
    rarity: constant.ItemRarity.UNCOMMON,
    category: [
      constant.Category.DAMAGE,
    ],
    unlock: {
      name: "Rapidfire",
      description: "The achievement is obtained by reaching +200% attack speed.",
      link: "https://riskofrain2.fandom.com/wiki/Rapidfire",
    },
    id: 19,
    stats: [{
      stat: constant.StatType.ATTACK_SPEED_CAP,
      value: "36%",
      stackType: constant.StackType.LINEAR,
      stackValue: "+24%", 
    },
    {
      stat: constant.StatType.CRITICAL_STRIKE_CHANCE,
      value: "5%",
      stackType: constant.StackType.NONE,
      stackValue: "+0%", 
    }],
  },
  20: {
    wikiLink: "https://riskofrain2.fandom.com/wiki/Tri-Tip_Dagger",
    name: "Tri-Tip Dagger",
    image: "https://vignette.wikia.nocookie.net/riskofrain2/images/1/17/Tri-Tip_Dagger.png/revision/latest?cb=20190411035144",
    shortDescription: "Chance to bleed enemies on hit.",
    description: "15% (+15% per stack) chance to bleed an enemy for 240% base damage.",
    rarity: constant.ItemRarity.COMMON,
    category: [
      constant.Category.DAMAGE,
    ],
    id: 20,
    stats: [{
      stat: constant.StatType.CHANCE,
      value: "15%",
      stackType: constant.StackType.LINEAR,
      stackValue: "+15%",
      effectiveMax: 7, 
    }],
  },
  21: {
    wikiLink: "https://riskofrain2.fandom.com/wiki/Red_Whip",
    name: "Red Whip",
    image: "https://vignette.wikia.nocookie.net/riskofrain2/images/2/2a/Red_Whip.png/revision/latest?cb=20191217215522",
    shortDescription: "Move fast out of combat.",
    description: "Leaving combat boosts your movement speed by 30% (+30% per stack).",
    rarity: constant.ItemRarity.UNCOMMON,
    category: [
      constant.Category.UTILITY,
    ],
    id: 21,
    stats: [{
      stat: constant.StatType.MOVEMENT_SPEED,
      value: "30%",
      stackType: constant.StackType.LINEAR,
      stackValue: "+30%", 
    }],
  },
  22: {
    wikiLink: "https://riskofrain2.fandom.com/wiki/H3AD-5T_v2",
    name: "H3AD-5T v2",
    image: "https://vignette.wikia.nocookie.net/riskofrain2/images/3/36/H3AD-5T_v2.png/revision/latest?cb=20190411034803",
    shortDescription: "Increase jump height. Hold 'Use' to slam down to the ground.",
    description: "Increase jump height. Creates a 10m radius kinetic explosion on hitting the ground, dealing 2300% base damage that scales up with speed. Recharges in 10 (-50% per stack) seconds.",
    rarity: constant.ItemRarity.LEGENDARY,
    category: [
      constant.Category.DAMAGE,
      constant.Category.UTILITY,
      constant.Category.AI_BLACKLIST,
    ],
    id: 22,
    stats: [{
      stat: constant.StatType.COOLDOWN,
      value: "10s",
      stackType: constant.StackType.EXPONENTIAL,
      stackValue: "-50%",
      effectiveMax: 7, 
    }],
  },
  24: {
    wikiLink: "https://riskofrain2.fandom.com/wiki/Warbanner",
    name: "Warbanner",
    image: "https://vignette.wikia.nocookie.net/riskofrain2/images/f/f0/Warbanner.png/revision/latest?cb=20190411035204",
    shortDescription: "Drop a Warbanner on leveling up, giving you great strength.",
    description: "On level up drop a banner that strengthens all allies within 16m (+8m per stack). Raise attack and movement speed by 30%.",
    rarity: constant.ItemRarity.COMMON,
    category: [
      constant.Category.UTILITY,
      constant.Category.AI_BLACKLIST,
    ],
    id: 24,
    stats: [{
      stat: constant.StatType.RADIUS,
      value: "16m",
      stackType: constant.StackType.LINEAR,
      stackValue: "+8m", 
    }],
  },
  25: {
    wikiLink: "https://riskofrain2.fandom.com/wiki/Old_War_Stealthkit",
    name: "Old War Stealthkit",
    image: "https://vignette.wikia.nocookie.net/riskofrain2/images/2/2c/Old_War_Stealthkit.png/revision/latest?cb=20190411034930",
    shortDescription: "Turn invisible on taking heavy damage.",
    description: "Chance on taking damage to gain 40% movement speed and invisibility for 3s (+1.5s per stack). Chance increases the more damage you take.",
    rarity: constant.ItemRarity.UNCOMMON,
    category: [
      constant.Category.UTILITY,
    ],
    id: 25,
    stats: [{
      stat: constant.StatType.DURATION,
      value: "3s",
      stackType: constant.StackType.LINEAR,
      stackValue: "+1.5s", 
    }],
  },
  26: {
    wikiLink: "https://riskofrain2.fandom.com/wiki/Harvester%27s_Scythe",
    name: "Harvester's Scythe",
    image: "https://vignette.wikia.nocookie.net/riskofrain2/images/e/e1/Harvester%27s_Scythe.png/revision/latest?cb=20190411034817",
    shortDescription: "'Critical Strikes' heal you.",
    description: "Gain 5% critical chance (+0% per stack). Critical strikes heal for 8 (+4 per stack) health.",
    rarity: constant.ItemRarity.UNCOMMON,
    category: [
      constant.Category.HEALING,
    ],
    unlock: {
      name: "Prismatically Aligned",
      description: "The achievement is obtained by completing a Prismatic Trial.",
      link: "https://riskofrain2.fandom.com/wiki/Prismatically_Aligned",
    },
    id: 26,
    stats: [{
      stat: constant.StatType.HEAL,
      value: "8",
      stackType: constant.StackType.LINEAR,
      stackValue: "+4", 
    },
    {
      stat: constant.StatType.CRITICAL_STRIKE_CHANCE,
      value: "5%",
      stackType: constant.StackType.NONE,
      stackValue: "+0%", 
    }],
  },
  27: {
    wikiLink: "https://riskofrain2.fandom.com/wiki/Cautious_Slug",
    name: "Cautious Slug",
    image: "https://vignette.wikia.nocookie.net/riskofrain2/images/c/c6/Cautious_Slug.png/revision/latest?cb=20190411034350",
    shortDescription: "Rapidly heal outside of danger.",
    description: "Increases passive health regeneration by 3 hp/s (+3 hp/s per stack) while outside of combat.",
    rarity: constant.ItemRarity.COMMON,
    category: [
      constant.Category.HEALING,
    ],
    id: 27,
    stats: [{
      stat: constant.StatType.HEALTH_REGENERATION,
      value: "3hp/s",
      stackType: constant.StackType.LINEAR,
      stackValue: "+3hp/s", 
    }],
  },
  29: {
    wikiLink: "https://riskofrain2.fandom.com/wiki/Personal_Shield_Generator",
    name: "Personal Shield Generator",
    image: "https://vignette.wikia.nocookie.net/riskofrain2/images/e/e0/Personal_Shield_Generator.png/revision/latest?cb=20190411034939",
    shortDescription: "Gain a recharging shield.",
    description: "Gain a shield equal to 8% (+8% per stack) of your maximum health. Recharges outside of danger.",
    rarity: constant.ItemRarity.COMMON,
    category: [
      constant.Category.UTILITY,
    ],
    id: 29,
    stats: [{
      stat: constant.StatType.SHIELD,
      value: "8%",
      stackType: constant.StackType.LINEAR,
      stackValue: "+8%", 
    }],
  },
  30: {
    wikiLink: "https://riskofrain2.fandom.com/wiki/Fuel_Cell",
    name: "Fuel Cell",
    image: "https://vignette.wikia.nocookie.net/riskofrain2/images/4/4d/Fuel_Cell.png/revision/latest?cb=20190411034744",
    shortDescription: "Hold an additional equipment charge. Reduce equipment cooldown.",
    description: "Hold an additional equipment charge (+1 per stack). Reduce equipment cooldown by 15% (+15% per stack).",
    rarity: constant.ItemRarity.UNCOMMON,
    category: [
      constant.Category.UTILITY,
      constant.Category.ON_KILL_EFFECT,
      constant.Category.EQUIPMENT_RELATED,
    ],
    unlock: {
      name: "Experimenting",
      description: "The achievement is obtained by picking up 5 different types of Equipment.",
      link: "https://riskofrain2.fandom.com/wiki/Experimenting",
    },
    id: 30,
    stats: [{
      stat: constant.StatType.CHARGE,
      value: "1",
      stackType: constant.StackType.LINEAR,
      stackValue: "+1",
      effectiveMax: 254, 
    },
    {
      stat: constant.StatType.COOLDOWN,
      value: "15%",
      stackType: constant.StackType.EXPONENTIAL,
      stackValue: "+15%", 
      effectiveMax: 43,
    }],
  },
  31: {
    wikiLink: "https://riskofrain2.fandom.com/wiki/N%27kuhana%27s_Opinion",
    name: "N'kuhana's Opinion",
    image: "https://vignette.wikia.nocookie.net/riskofrain2/images/c/c9/N%27kuhana%27s_Opinion.png/revision/latest?cb=20190411034921",
    shortDescription: "Fire haunting skulls when healed.",
    description: "Store 100% (+100% per stack) of healing as Soul Energy. After your Soul Energy reaches 10% of your maximum health, fire a skull that deals 250% of your Soul Energy as damage.",
    rarity: constant.ItemRarity.LEGENDARY,
    category: [
      constant.Category.DAMAGE,
    ],
    unlock: {
      name: "Her Concepts",
      description: "The achievement is obtained by finding the Altar to N'kuhana.",
      link: "https://riskofrain2.fandom.com/wiki/Her_Concepts",
    },
    id: 31,
    stats: [{
      stat: constant.StatType.DAMAGE,
      value: "100%",
      stackType: constant.StackType.LINEAR,
      stackValue: "+100%", 
    }],
  },
  32: {
    wikiLink: "https://riskofrain2.fandom.com/wiki/Unstable_Tesla_Coil",
    name: "Unstable Tesla Coil",
    image: "https://vignette.wikia.nocookie.net/riskofrain2/images/e/e4/Unstable_Tesla_Coil.png/revision/latest?cb=20190411035154",
    shortDescription: "Shock all nearby enemies every 10 seconds.",
    description: "Fire out lightning that hits 3 (+2 per stack) enemies for 200% base damage every 0.5s. The Tesla Coil switches off every 10 seconds.",
    rarity: constant.ItemRarity.LEGENDARY,
    category: [
      constant.Category.DAMAGE,
    ],
    unlock: {
      name: "Macho",
      description: "The achievement is obtained by dealing 5000 damage in one shot.",
      link: "https://riskofrain2.fandom.com/wiki/Macho",
    },
    id: 32,
    stats: [{
      stat: constant.StatType.AMOUNT,
      value: "3",
      stackType: constant.StackType.LINEAR,
      stackValue: "+2", 
    }],
  },
  33: {
    wikiLink: "https://riskofrain2.fandom.com/wiki/Infusion",
    name: "Infusion",
    image: "https://vignette.wikia.nocookie.net/riskofrain2/images/7/7d/Infusion.png/revision/latest?cb=20190411034834",
    shortDescription: "Killing an enemy permanently increases your health, up to 100.",
    description: "Killing an enemy increases your health permanently by 1, up to a maximum of 100 (+100 per stack) health.",
    rarity: constant.ItemRarity.UNCOMMON,
    category: [
      constant.Category.UTILITY,
      constant.Category.HEALING,
      constant.Category.ON_KILL_EFFECT,
    ],
    unlock: {
      name: "Slaughter",
      description: "The achievement is obtained by defeating 3000 enemies.",
      link: "https://riskofrain2.fandom.com/wiki/Slaughter",
    },
    id: 33,
    stats: [{
      stat: constant.StatType.TOTAL_HEALTH,
      value: "100",
      stackType: constant.StackType.LINEAR,
      stackValue: "+100", 
    }],
  },
  35: {
    wikiLink: "https://riskofrain2.fandom.com/wiki/57_Leaf_Clover",
    name: "57 Leaf Clover",
    image: "https://vignette.wikia.nocookie.net/riskofrain2/images/e/e5/57_Leaf_Clover.png/revision/latest?cb=20190411034200",
    shortDescription: "Luck is on your side.",
    description: "All random effects are rolled +1 (+1 per stack) times for a favorable outcome.",
    rarity: constant.ItemRarity.LEGENDARY,
    category: [
      constant.Category.UTILITY,
    ],
    unlock: {
      name: "The Long Road",
      description: "The achievement is obtained by completing 20 stages in a single run.",
      link: "https://riskofrain2.fandom.com/wiki/The_Long_Road",
    },
    id: 35,
    stats: [{
      stat: constant.StatType.LUCK,
      value: "1",
      stackType: constant.StackType.EXPONENTIAL,
      stackValue: "+1", 
    }],
  },
  36: {
    wikiLink: "https://riskofrain2.fandom.com/wiki/Medkit",
    name: "Medkit",
    image: "https://vignette.wikia.nocookie.net/riskofrain2/images/0/0f/Medkit.png/revision/latest?cb=20190411034907",
    shortDescription: "Receive a delayed heal after taking damage.",
    description: "Heal for 10 (+10 per stack) health 1.1 seconds after getting hurt.",
    rarity: constant.ItemRarity.COMMON,
    category: [
      constant.Category.HEALING,
    ],
    unlock: {
      name: "Elite Slayer",
      description: "The achievement is obtained by defeating an Elite-type monster.",
      link: "https://riskofrain2.fandom.com/wiki/Elite_Slayer",
    },
    id: 36,
    stats: [{
      stat: constant.StatType.HEAL,
      value: "10",
      stackType: constant.StackType.LINEAR,
      stackValue: "+10", 
    }],
  },
  37: {
    wikiLink: "https://riskofrain2.fandom.com/wiki/Bandolier",
    name: "Bandolier",
    image: "https://vignette.wikia.nocookie.net/riskofrain2/images/6/62/Bandolier.png/revision/latest?cb=20190411034319",
    shortDescription: "Chance on kill to drop an ammo pack that resets all skill cooldowns.",
    description: "18% (+10% per stack) chance on kill to drop an ammo pack that resets all skill cooldowns.",
    rarity: constant.ItemRarity.UNCOMMON,
    category: [
      constant.Category.UTILITY,
      constant.Category.ON_KILL_EFFECT,
    ],
    id: 37,
    stats: [{
      stat: constant.StatType.CHANCE,
      value: "18%",
      stackType: constant.StackType.HYPERBOLIC,
      stackValue: "+10%", 
    }],
  },
  38: {
    wikiLink: "https://riskofrain2.fandom.com/wiki/Sentient_Meat_Hook",
    name: "Sentient Meat Hook",
    image: "https://vignette.wikia.nocookie.net/riskofrain2/images/e/e7/Sentient_Meat_Hook.png/revision/latest?cb=20190411035050",
    shortDescription: "Chance to hook all nearby enemies.",
    description: "20% (+20% per stack) chance on hit to fire homing hooks at up to 10 (+5 per stack) enemies for 100% TOTAL damage.",
    rarity: constant.ItemRarity.LEGENDARY,
    category: [
      constant.Category.DAMAGE,
    ],
    unlock: {
      name: "Deja Vu?",
      description: "The achievement is obtained by looping back to the first stage.",
      link: "https://riskofrain2.fandom.com/wiki/Deja_Vu%3F",
    },
    id: 38,
    stats: [{
      stat: constant.StatType.CHANCE,
      value: "20%",
      stackType: constant.StackType.HYPERBOLIC,
      stackValue: "+20%", 
    },
    {
      stat: constant.StatType.AMOUNT,
      value: "10",
      stackType: constant.StackType.LINEAR,
      stackValue: "+5", 
    }],
  },
  39: {
    wikiLink: "https://riskofrain2.fandom.com/wiki/Gasoline",
    name: "Gasoline",
    image: "https://vignette.wikia.nocookie.net/riskofrain2/images/6/6e/Gasoline.png/revision/latest?cb=20190411034748",
    shortDescription: "Killing enemies sets nearby enemies on fire.",
    description: "Killing an enemy ignites all enemies within 12m (+4m per stack). Enemies burn for 150% (+75% per stack) base damage.",
    rarity: constant.ItemRarity.COMMON,
    category: [
      constant.Category.DAMAGE,
      constant.Category.ON_KILL_EFFECT,
    ],
    id: 39,
    stats: [{
      stat: constant.StatType.DAMAGE,
      value: "150%",
      stackType: constant.StackType.LINEAR,
      stackValue: "+75%", 
    },
    {
      stat: constant.StatType.RADIUS,
      value: "12m",
      stackType: constant.StackType.LINEAR,
      stackValue: "+4m", 
    }],
  },
  41: {
    wikiLink: "https://riskofrain2.fandom.com/wiki/Stun_Grenade",
    name: "Stun Grenade",
    image: "https://vignette.wikia.nocookie.net/riskofrain2/images/2/27/Stun_Grenade.png/revision/latest?cb=20190411035113",
    shortDescription: "Chance to stun on hit.",
    description: "5% (+5% on stack) chance on hit to stun enemies for 2 seconds.",
    rarity: constant.ItemRarity.COMMON,
    category: [
      constant.Category.UTILITY,
      constant.Category.AI_BLACKLIST,
    ],
    id: 41,
    stats: [{
      stat: constant.StatType.CHANCE,
      value: "5%",
      stackType: constant.StackType.HYPERBOLIC,
      stackValue: "+5%", 
    }],
  },
  42: {
    wikiLink: "https://riskofrain2.fandom.com/wiki/Bundle_of_Fireworks",
    name: "Bundle of Fireworks",
    image: "https://vignette.wikia.nocookie.net/riskofrain2/images/3/3d/Bundle_of_Fireworks.png/revision/latest?cb=20190411034341",
    shortDescription: "Activating an interactable launches fireworks at nearby enemies.",
    description: "Activating an interactable launches 8 (+4 per stack) fireworks that deal 300% base damage.",
    rarity: constant.ItemRarity.COMMON,
    category: [
      constant.Category.DAMAGE,
      constant.Category.AI_BLACKLIST,
    ],
    unlock: {
      name: "...Maybe One More",
      description: "The achievement is obtained by duplicating the same item 7 times in a row with a 3D Printer.",
      link: "https://riskofrain2.fandom.com/wiki/...Maybe_One_More",
    },
    id: 42,
    stats: [{
      stat: constant.StatType.AMOUNT,
      value: "8",
      stackType: constant.StackType.LINEAR,
      stackValue: "+4", 
    }],
  },
  43: {
    wikiLink: "https://riskofrain2.fandom.com/wiki/Shaped_Glass",
    name: "Shaped Glass",
    image: "https://vignette.wikia.nocookie.net/riskofrain2/images/f/ff/Shaped_Glass.png/revision/latest?cb=20190411035054",
    shortDescription: "Double your damage... BUT halve your health.",
    description: "Increase base damage by 100% (+100% per stack). Reduce maximum health by 50% (+50% per stack).",
    rarity: constant.ItemRarity.LUNAR,
    category: [
      constant.Category.DAMAGE,
    ],
    id: 43,
    stats: [{
      stat: constant.StatType.DAMAGE,
      value: "100%",
      stackType: constant.StackType.EXPONENTIAL,
      stackValue: "+100%", 
    },
    {
      stat: constant.StatType.TOTAL_HEALTH,
      value: "-50%",
      stackType: constant.StackType.EXPONENTIAL,
      stackValue: "-50%",
      effectiveMax: 127, 
    }],
  },
  44: {
    wikiLink: "https://riskofrain2.fandom.com/wiki/Brittle_Crown",
    name: "Brittle Crown",
    image: "https://vignette.wikia.nocookie.net/riskofrain2/images/a/ae/Brittle_Crown.png/revision/latest?cb=20190411034336",
    shortDescription: "Gain gold on hit... BUT lose gold on getting hit.",
    description: "30% chance on hit to gain 2 gold (+2 per stack). Scales over time.\n\nLose gold on taking damage equal to 100% (+100% per stack) of the maximum health percentage you lost.",
    rarity: constant.ItemRarity.LUNAR,
    category: [
      constant.Category.UTILITY,
    ],
    id: 44,
    stats: [{
      stat: constant.StatType.GOLD,
      value: "2",
      stackType: constant.StackType.LINEAR,
      stackValue: "+2", 
    },
    {
      stat: constant.StatType.GOLD,
      value: "100%",
      stackType: constant.StackType.LINEAR,
      stackValue: "+100%", 
    }],
  },
  46: {
    wikiLink: "https://riskofrain2.fandom.com/wiki/Berzerker%27s_Pauldron",
    name: "Berzerker's Pauldron",
    image: "https://vignette.wikia.nocookie.net/riskofrain2/images/a/a6/Berzerker%27s_Pauldron.png/revision/latest?cb=20190411034324",
    shortDescription: "Enter a frenzy after killing 3 enemies in quick succession.",
    description: "Killing 3 enemies within 1 second sends you into a frenzy for 6s (+4s per stack). Increases movement speed by 50% and attack speed by 100%.",
    rarity: constant.ItemRarity.UNCOMMON,
    category: [
      constant.Category.DAMAGE,
      constant.Category.ON_KILL_EFFECT,
    ],
    unlock: {
      name: "Glorious Battle",
      description: "The achievement is obtained by completing the Teleporter event with less than 10% health.",
      link: "https://riskofrain2.fandom.com/wiki/Glorious_Battle",
    },
    id: 46,
    stats: [{
      stat: constant.StatType.DURATION,
      value: "6s",
      stackType: constant.StackType.LINEAR,
      stackValue: "+4s", 
    }],
  },
  49: {
    wikiLink: "https://riskofrain2.fandom.com/wiki/Transcendence",
    name: "Transcendence",
    image: "https://vignette.wikia.nocookie.net/riskofrain2/images/8/85/Transcendence.png/revision/latest?cb=20190411035139",
    shortDescription: "Convert all your health into shield. Increase maximum health.",
    description: "Convert all but 1 health into regenerating shields. Gain 50% (+25% per stack) maximum health.",
    rarity: constant.ItemRarity.LUNAR,
    category: [
      constant.Category.UTILITY,
    ],
    id: 49,
    stats: [{
      stat: constant.StatType.TOTAL_HEALTH,
      value: "50%",
      stackType: constant.StackType.LINEAR,
      stackValue: "+25%", 
    }],
  },
  50: {
    wikiLink: "https://riskofrain2.fandom.com/wiki/Alien_Head",
    name: "Alien Head",
    image: "https://vignette.wikia.nocookie.net/riskofrain2/images/2/25/Alien_Head.png/revision/latest?cb=20190411034301",
    shortDescription: "Reduces cooldowns for your skills.",
    description: "Reduce skill cooldowns by 25% (+25% per stack).",
    rarity: constant.ItemRarity.LEGENDARY,
    category: [
      constant.Category.UTILITY,
    ],
    id: 50,
    stats: [{
      stat: constant.StatType.COOLDOWN,
      value: "25%",
      stackType: constant.StackType.EXPONENTIAL,
      stackValue: "+25%",
      effectiveMax: 19, 
    }],
  },
  51: {
    wikiLink: "https://riskofrain2.fandom.com/wiki/Soulbound_Catalyst",
    name: "Soulbound Catalyst",
    image: "https://vignette.wikia.nocookie.net/riskofrain2/images/f/f1/Soulbound_Catalyst.png/revision/latest?cb=20190411035105",
    shortDescription: "Kills reduce equipment cooldown.",
    description: "Kills reduce equipment cooldown by 4s (+2s per stack).",
    rarity: constant.ItemRarity.LEGENDARY,
    category: [
      constant.Category.UTILITY,
      constant.Category.ON_KILL_EFFECT,
      constant.Category.EQUIPMENT_RELATED,
    ],
    unlock: {
      name: "Newtist",
      description: "The achievement is obtained by activating 8 unique Newt Altars.",
      link: "https://riskofrain2.fandom.com/wiki/Newtist",
    },
    id: 51,
    stats: [{
      stat: constant.StatType.COOLDOWN,
      value: "4s",
      stackType: constant.StackType.LINEAR,
      stackValue: "+2s",
      effectiveMax: 69, 
    }],
  },
  52: {
    wikiLink: "https://riskofrain2.fandom.com/wiki/Titanic_Knurl",
    name: "Titanic Knurl",
    image: "https://vignette.wikia.nocookie.net/riskofrain2/images/9/9f/Titanic_Knurl.png/revision/latest?cb=20190411035129",
    shortDescription: "Boosts health and regeneration.",
    description: "Increase maximum health by 40 (+40 per stack) and health regeneration by 1.6 (+1.6 per stack) health / second.",
    rarity: constant.ItemRarity.BOSS,
    dropsFrom: "Stone Titan",
    category: [
      constant.Category.UTILITY,
      constant.Category.HEALING,
    ],
    id: 52,
    stats: [{
      stat: constant.StatType.TOTAL_HEALTH,
      value: "40",
      stackType: constant.StackType.LINEAR,
      stackValue: "+40", 
    },
    {
      stat: constant.StatType.HEALTH_REGENERATION,
      value: "1.6",
      stackType: constant.StackType.LINEAR,
      stackValue: "+1.6", 
    }],
  },
  57: {
    wikiLink: "https://riskofrain2.fandom.com/wiki/Energy_Drink",
    name: "Energy Drink",
    image: "https://vignette.wikia.nocookie.net/riskofrain2/images/7/7e/Energy_Drink.png/revision/latest?cb=20190411034729",
    shortDescription: "Sprint faster.",
    description: "Sprint speed is improved by 30% (+20% per stack).",
    rarity: constant.ItemRarity.COMMON,
    category: [
      constant.Category.UTILITY,
      constant.Category.SPRINT_RELATED,
    ],
    id: 57,
    stats: [{
      stat: constant.StatType.SPRINT_SPEED,
      value: "30%",
      stackType: constant.StackType.LINEAR,
      stackValue: "+20%", 
    }],
  },
  58: {
    wikiLink: "https://riskofrain2.fandom.com/wiki/Backup_Magazine",
    name: "Backup Magazine",
    image: "https://vignette.wikia.nocookie.net/riskofrain2/images/f/f3/Backup_Magazine.png/revision/latest?cb=20190411034315",
    shortDescription: "Add an extra charge of your Secondary skill.",
    description: "Add +1 (+1 per stack) charge of your Secondary skill.",
    rarity: constant.ItemRarity.COMMON,
    category: [
      constant.Category.UTILITY,
    ],
    unlock: {
      name: "Flawless",
      description: "The achievement is obtained by charging a Teleporter without getting hit.",
      link: "https://riskofrain2.fandom.com/wiki/Flawless",
    },
    id: 58,
    stats: [{
      stat: constant.StatType.CHARGE,
      value: "1",
      stackType: constant.StackType.LINEAR,
      stackValue: "+1", 
    }],
  },
  59: {
    wikiLink: "https://riskofrain2.fandom.com/wiki/Sticky_Bomb",
    name: "Sticky Bomb",
    image: "https://vignette.wikia.nocookie.net/riskofrain2/images/7/74/Sticky_Bomb.png/revision/latest?cb=20190411035109",
    shortDescription: "Chance on hit to attach a bomb to enemies.",
    description: "5% (+5% per stack) chance on hit to attach a bomb to an enemy, detonating for 180% TOTAL damage.",
    rarity: constant.ItemRarity.COMMON,
    category: [
      constant.Category.DAMAGE,
    ],
    id: 59,
    stats: [{
      stat: constant.StatType.CHANCE,
      value: "5%",
      stackType: constant.StackType.LINEAR,
      stackValue: "+5%",
      effectiveMax: 20, 
    }],
  },
  60: {
    wikiLink: "https://riskofrain2.fandom.com/wiki/Rusted_Key",
    name: "Rusted Key",
    image: "https://vignette.wikia.nocookie.net/riskofrain2/images/9/9b/Rusted_Key.png/revision/latest?cb=20190411035027",
    shortDescription: "Gain access to a Rusty Lockbox that contains treasure.",
    description: "A hidden cache containing an item will appear in a random location on each stage. (Increases rarity of the item per stack).",
    rarity: constant.ItemRarity.COMMON,
    category: [
      constant.Category.UTILITY,
      constant.Category.AI_BLACKLIST,
    ],
    unlock: {
      name: "Keyed Up",
      description: "The achievement is obtained by defeating a Teleporter boss under 15 seconds.",
      link: "https://riskofrain2.fandom.com/wiki/Keyed_Up",
    },
    id: 60,
    stats: [{
      stat: constant.StatType.CHANCE,
      value: "",
      stackType: constant.StackType.SPECIAL,
      stackValue: "", 
    }],
  },
  61: {
    wikiLink: "https://riskofrain2.fandom.com/wiki/Armor-Piercing_Rounds",
    name: "Armor-Piercing Rounds",
    image: "https://vignette.wikia.nocookie.net/riskofrain2/images/f/f0/Armor-Piercing_Rounds.png/revision/latest?cb=20190411034306",
    shortDescription: "Deal extra damage to bosses.",
    description: "Deal an additional 20% damage (+20% per stack) to bosses.",
    rarity: constant.ItemRarity.COMMON,
    category: [
      constant.Category.DAMAGE,
      constant.Category.AI_BLACKLIST,
    ],
    unlock: {
      name: "Advancement",
      description: "The achievement is obtained by completing a Teleporter Event.",
      link: "https://riskofrain2.fandom.com/wiki/Advancement",
    },
    id: 61,
    stats: [{
      stat: constant.StatType.DAMAGE,
      value: "20%",
      stackType: constant.StackType.LINEAR,
      stackValue: "+20%", 
    }],
  },
  62: {
    wikiLink: "https://riskofrain2.fandom.com/wiki/Rose_Buckler",
    name: "Rose Buckler",
    image: "https://vignette.wikia.nocookie.net/riskofrain2/images/2/2f/Rose_Buckler.png/revision/latest?cb=20190411035015",
    shortDescription: "Reduce incoming damage while sprinting.",
    description: "Increase armor by 30 (+30 per stack) while sprinting.",
    rarity: constant.ItemRarity.UNCOMMON,
    category: [
      constant.Category.UTILITY,
      constant.Category.SPRINT_RELATED,
    ],
    id: 62,
    stats: [{
      stat: constant.StatType.ARMOUR,
      value: "30",
      stackType: constant.StackType.LINEAR,
      stackValue: "+30", 
    }],
  },
  63: {
    wikiLink: "https://riskofrain2.fandom.com/wiki/Runald%27s_Band",
    name: "Runald's Band",
    image: "https://vignette.wikia.nocookie.net/riskofrain2/images/0/05/Runald%27s_Band.png/revision/latest?cb=20190411035023",
    shortDescription: "Chance on hit to strike an enemy with a runic ice blast.",
    description: "8% chance on hit to strike an enemy with a runic ice blast, slowing them by 80% and dealing 250% (+125% per stack) TOTAL damage.",
    rarity: constant.ItemRarity.UNCOMMON,
    category: [
      constant.Category.DAMAGE,
    ],
    unlock: {
      name: "Death Do Us Part",
      description: "The achievement is obtained by discovering the hidden chamber in the Abandoned Aqueduct.",
      link: "https://riskofrain2.fandom.com/wiki/Death_Do_Us_Part",
    },
    id: 63,
    stats: [{
      stat: constant.StatType.DAMAGE,
      value: "250%",
      stackType: constant.StackType.LINEAR,
      stackValue: "+125%", 
    }],
  },
  64: {
    wikiLink: "https://riskofrain2.fandom.com/wiki/Kjaro%27s_Band",
    name: "Kjaro's Band",
    image: "https://vignette.wikia.nocookie.net/riskofrain2/images/e/eb/Kjaro%27s_Band.png/revision/latest?cb=20190411034838",
    shortDescription: "Chance on hit to strike an enemy with a runic flame tornado.",
    description: "8% chance on hit to strike an enemy with a runic flame tornado, dealing 500% (+250% per stack) TOTAL damage.",
    rarity: constant.ItemRarity.UNCOMMON,
    category: [
      constant.Category.DAMAGE,
    ],
    unlock: {
      name: "Death Do Us Part",
      description: "The achievement is obtained by discovering the hidden chamber in the Abandoned Aqueduct.",
      link: "https://riskofrain2.fandom.com/wiki/Death_Do_Us_Part",
    },
    id: 64,
    stats: [{
      stat: constant.StatType.DAMAGE,
      value: "500%",
      stackType: constant.StackType.LINEAR,
      stackValue: "+250%", 
    }],
  },
  65: {
    wikiLink: "https://riskofrain2.fandom.com/wiki/Chronobauble",
    name: "Chronobauble",
    image: "https://vignette.wikia.nocookie.net/riskofrain2/images/3/38/Chronobauble.png/revision/latest?cb=20190411034359",
    shortDescription: "Slow enemies on hit.",
    description: "Slow enemies on hit for -60% movement speed for 2s (+2s per stack).",
    rarity: constant.ItemRarity.UNCOMMON,
    category: [
      constant.Category.UTILITY,
    ],
    id: 65,
    stats: [{
      stat: constant.StatType.SLOW_DURATION,
      value: "2s",
      stackType: constant.StackType.LINEAR,
      stackValue: "+2s", 
    }],
  },
  66: {
    wikiLink: "https://riskofrain2.fandom.com/wiki/Dio%27s_Best_Friend",
    name: "Dio's Best Friend",
    image: "https://vignette.wikia.nocookie.net/riskofrain2/images/d/dc/Dio%27s_Best_Friend.png/revision/latest?cb=20190411034412",
    shortDescription: "Cheat death. Consumed on use.",
    description: "Upon death, this item will be consumed and you will return to life with 3 seconds of invulnerability.",
    rarity: constant.ItemRarity.LEGENDARY,
    category: [
      constant.Category.UTILITY,
    ],
    unlock: {
      name: "The Lone Survivor",
      description: "The achievement is obtained by staying alive for 30 consecutive minutes.",
      link: "https://riskofrain2.fandom.com/wiki/The_Lone_Survivor",
    },
    id: 66,
    stats: [{
      stat: constant.StatType.CHARGE,
      value: "1",
      stackType: constant.StackType.LINEAR,
      stackValue: "+1", 
    }],
  },
  68: {
    wikiLink: "https://riskofrain2.fandom.com/wiki/Hardlight_Afterburner",
    name: "Hardlight Afterburner",
    image: "https://vignette.wikia.nocookie.net/riskofrain2/images/2/20/Hardlight_Afterburner.png/revision/latest?cb=20190411034812",
    shortDescription: "Add 2 extra charges of your Utility skill. Reduce Utility skill cooldown.",
    description: "Add +2 (+2 per stack) charges of your Utility skill. Reduces Utility skill cooldown by 33%.",
    rarity: constant.ItemRarity.LEGENDARY,
    category: [
      constant.Category.UTILITY,
    ],
    id: 68,
    stats: [{
      stat: constant.StatType.CHARGE,
      value: "2",
      stackType: constant.StackType.LINEAR,
      stackValue: "+2", 
    }],
  },
  69: {
    wikiLink: "https://riskofrain2.fandom.com/wiki/Wake_of_Vultures",
    name: "Wake of Vultures",
    image: "https://vignette.wikia.nocookie.net/riskofrain2/images/f/f8/Wake_of_Vultures.png/revision/latest?cb=20190411035159",
    shortDescription: "Temporarily steal the power of slain elites.",
    description: "Gain the power of any killed elite monster for 8s (+5s per stack).",
    rarity: constant.ItemRarity.LEGENDARY,
    category: [
      constant.Category.DAMAGE,
      constant.Category.UTILITY,
      constant.Category.AI_BLACKLIST,
      constant.Category.ON_KILL_EFFECT,
    ],
    id: 69,
    stats: [{
      stat: constant.StatType.DURATION,
      value: "8s",
      stackType: constant.StackType.LINEAR,
      stackValue: "+5s", 
    }],
  },
  70: {
    wikiLink: "https://riskofrain2.fandom.com/wiki/Brainstalks",
    name: "Brainstalks",
    image: "https://vignette.wikia.nocookie.net/riskofrain2/images/c/c0/Brainstalks.png/revision/latest?cb=20190411034328",
    shortDescription: "Skills have NO cooldowns for a short period after killing an elite.",
    description: "Upon killing an elite monster, enter a frenzy for 4s (+4s per stack) where skills have no cooldowns.",
    rarity: constant.ItemRarity.LEGENDARY,
    category: [
      constant.Category.UTILITY,
      constant.Category.AI_BLACKLIST,
      constant.Category.ON_KILL_EFFECT,
    ],
    unlock: {
      name: "Decide",
      description: "The achievement is obtained by defeating an Elite boss on Monsoon difficulty.",
      link: "https://riskofrain2.fandom.com/wiki/Deicide",
    },
    id: 70,
    stats: [{
      stat: constant.StatType.DURATION,
      value: "4s",
      stackType: constant.StackType.LINEAR,
      stackValue: "+4s", 
    }],
  },
  71: {
    wikiLink: "https://riskofrain2.fandom.com/wiki/Corpsebloom",
    name: "Corpsebloom",
    image: "https://vignette.wikia.nocookie.net/riskofrain2/images/3/31/Corpsebloom.png/revision/latest?cb=20190411034403",
    shortDescription: "Double your healing... BUT it's applied over time.",
    description: "Heal +100% (+100% per stack) more. All healing is applied over time. Can heal for a maximum of 10% (reduced by 50% per stack) of your health per second.",
    rarity: constant.ItemRarity.LUNAR,
    category: [
      constant.Category.HEALING,
    ],
    id: 71,
    stats: [{
      stat: constant.StatType.HEAL,
      value: "100%",
      stackType: constant.StackType.LINEAR,
      stackValue: "+100%", 
    },
    {
      stat: constant.StatType.HEAL_RATE,
      value: "10%",
      stackType: constant.StackType.EXPONENTIAL,
      stackValue: "-50%", 
      effectiveMax: 7,
    }],
  },
  74: {
    wikiLink: "https://riskofrain2.fandom.com/wiki/Gesture_of_the_Drowned",
    name: "Gesture of the Drowned",
    image: "https://vignette.wikia.nocookie.net/riskofrain2/images/c/c9/Gesture_of_the_Drowned.png/revision/latest?cb=20190411034753",
    shortDescription: "Dramatically reduce Equipment cooldown... BUT it automatically activates.",
    description: "Reduce Equipment cooldown by 50% (+15% per stack). Forces your Equipment to activate whenever it is off cooldown.",
    rarity: constant.ItemRarity.LUNAR,
    category: [
      constant.Category.UTILITY,
      constant.Category.EQUIPMENT_RELATED,
    ],
    unlock: {
      name: "The Demons And The Crabs",
      description: "The achievement is obtained by killing 20 Hermit Crabs by chasing them off the edge of the map.",
      link: "https://riskofrain2.fandom.com/wiki/The_Demons_And_The_Crabs",
    },
    id: 74,
    stats: [{
      stat: constant.StatType.COOLDOWN,
      value: "-50%",
      stackType: constant.StackType.EXPONENTIAL,
      stackValue: "-15%",
      effectiveMax: 40, 
    }],
  },
  75: {
    wikiLink: "https://riskofrain2.fandom.com/wiki/Rejuvenation_Rack",
    name: "Rejuvenation Rack",
    image: "https://vignette.wikia.nocookie.net/riskofrain2/images/0/0a/Rejuvenation_Rack.png/revision/latest?cb=20190411035011",
    shortDescription: "Double the strength of healing.",
    description: "Heal +100% (+100% per stack) more.",
    rarity: constant.ItemRarity.LEGENDARY,
    category: [
      constant.Category.HEALING,
    ],
    unlock: {
      name: "Naturopath",
      description: "The achievement is obtained by reaching and completing the 3rd Teleporter Event without healing.",
      link: "https://riskofrain2.fandom.com/wiki/Naturopath",
    },
    id: 75,
    stats: [{
      stat: constant.StatType.HEAL,
      value: "100%",
      stackType: constant.StackType.LINEAR,
      stackValue: "+100%", 
    }],
  },
  76: {
    wikiLink: "https://riskofrain2.fandom.com/wiki/Wax_Quail",
    name: "Wax Quail",
    image: "https://vignette.wikia.nocookie.net/riskofrain2/images/6/6c/Wax_Quail.png/revision/latest?cb=20190411035209",
    shortDescription: "Jumping while sprinting boosts you forward.",
    description: "Jumping while sprinting boosts you forward by 10m (+10m per stack).",
    rarity: constant.ItemRarity.UNCOMMON,
    category: [
      constant.Category.UTILITY,
      constant.Category.SPRINT_RELATED,
    ],
    unlock: {
      name: "Going Fast Recommended",
      description: "The achievement is obtained by reaching +300% movespeed, including sprinting.",
      link: "https://riskofrain2.fandom.com/wiki/Going_Fast_Recommended",
    },
    id: 76,
    stats: [{
      stat: constant.StatType.BOOST,
      value: "10m",
      stackType: constant.StackType.LINEAR,
      stackValue: "+10m", 
    }],
  },
  78: {
    wikiLink: "https://riskofrain2.fandom.com/wiki/Old_Guillotine",
    name: "Old Guillotine",
    image: "https://vignette.wikia.nocookie.net/riskofrain2/images/8/8d/Old_Guillotine.png/revision/latest?cb=20190918043207",
    shortDescription: "Instantly kill low health Elite monsters.",
    description: "Instantly kill Elite monsters below 20% (+20% per stack) health.",
    rarity: constant.ItemRarity.UNCOMMON,
    category: [
      constant.Category.DAMAGE,
      constant.Category.AI_BLACKLIST,
    ],
    id: 78,
    stats: [{
      stat: constant.StatType.THRESHOLD,
      value: "20%",
      stackType: constant.StackType.HYPERBOLIC,
      stackValue: "+20%", 
    }],
  },
  79: {
    wikiLink: "https://riskofrain2.fandom.com/wiki/War_Horn",
    name: "War Horn",
    image: "https://vignette.wikia.nocookie.net/riskofrain2/images/9/9c/War_Horn.png/revision/latest?cb=20190625193716",
    shortDescription: "Activating your Equipment gives you a burst of attack speed.",
    description: "Activating your Equipment gives you +70% attack speed for 8s (+4s per stack).",
    rarity: constant.ItemRarity.UNCOMMON,
    category: [
      constant.Category.DAMAGE,
      constant.Category.EQUIPMENT_RELATED,
    ],
    unlock: {
      name: "Warmonger",
      description: "The achievement is obtained by completing 3 Combat Shrines in a single stage.",
      link: "https://riskofrain2.fandom.com/wiki/Warmonger",
    },
    id: 79,
    stats: [{
      stat: constant.StatType.DURATION,
      value: "8s",
      stackType: constant.StackType.LINEAR,
      stackValue: "+4s", 
    }],
  },
  80: {
    wikiLink: "https://riskofrain2.fandom.com/wiki/Aegis",
    name: "Aegis",
    image: "https://vignette.wikia.nocookie.net/riskofrain2/images/e/e5/Aegis.png/revision/latest?cb=20190625193715",
    shortDescription: "Healing past full grants you a temporary barrier.",
    description: "Healing past full grants you a temporary barrier for 50% (+50% per stack) of the amount you healed.",
    rarity: constant.ItemRarity.LEGENDARY,
    category: [
      constant.Category.UTILITY,
      constant.Category.HEALING,
    ],
    id: 80,
    stats: [{
      stat: constant.StatType.SHIELD,
      value: "50%",
      stackType: constant.StackType.LINEAR,
      stackValue: "+50%", 
    }],
  },
  82: {
    wikiLink: "https://riskofrain2.fandom.com/wiki/Halcyon_Seed",
    name: "Halcyon Seed",
    image: "https://vignette.wikia.nocookie.net/riskofrain2/images/e/e6/Halcyon_Seed.png/revision/latest?cb=20190625193715",
    shortDescription: "Summon Aurelionite during the Teleporter event.",
    description: "Summon Aurelionite during the teleporter event. It has 100% (+50% per stack) damage and 100% (+100% per stack) health.",
    rarity: constant.ItemRarity.BOSS,
    dropsFrom: "Aurelionite",
    category: [
      constant.Category.UTILITY,
      constant.Category.WORLD_UNIQUE,
    ],
    id: 82,
    stats: [{
      stat: constant.StatType.ALLY_HEALTH,
      value: "100%",
      stackType: constant.StackType.LINEAR,
      stackValue: "+100%", 
    },
    {
      stat: constant.StatType.ALLY_DAMAGE,
      value: "100%",
      stackType: constant.StackType.LINEAR,
      stackValue: "+50%", 
    }],
  },
  83: {
    wikiLink: "https://riskofrain2.fandom.com/wiki/Little_Disciple",
    name: "Little Disciple",
    image: "https://vignette.wikia.nocookie.net/riskofrain2/images/0/08/Little_Disciple.png/revision/latest?cb=20190625193715",
    shortDescription: "Fire tracking wisps while sprinting.",
    description: "Fire a tracking wisp for 100% (+100% per stack) damage. Fires every 0.5 seconds while sprinting.",
    rarity: constant.ItemRarity.BOSS,
    dropsFrom: "Grovetender",
    category: [
      constant.Category.DAMAGE,
      constant.Category.SPRINT_RELATED,
    ],
    id: 83,
    stats: [{
      stat: constant.StatType.DAMAGE,
      value: "100%",
      stackType: constant.StackType.LINEAR,
      stackValue: "+100%", 
    }],
  },
  84: {
    wikiLink: "https://riskofrain2.fandom.com/wiki/Topaz_Brooch",
    name: "Topaz Brooch",
    image: "https://vignette.wikia.nocookie.net/riskofrain2/images/c/c5/Topaz_Brooch.png/revision/latest?cb=20190625193715",
    shortDescription: "Gain a temporary barrier on kill.",
    description: "Gain a temporary barrier on kill for 15 health (+15 per stack).",
    rarity: constant.ItemRarity.COMMON,
    category: [
      constant.Category.UTILITY,
      constant.Category.HEALING,
      constant.Category.ON_KILL_EFFECT,
    ],
    id: 84,
    stats: [{
      stat: constant.StatType.SHIELD,
      value: "15",
      stackType: constant.StackType.LINEAR,
      stackValue: "+15", 
    }],
  },
  85: {
    wikiLink: "https://riskofrain2.fandom.com/wiki/Shattering_Justice",
    name: "Shattering Justice",
    image: "https://vignette.wikia.nocookie.net/riskofrain2/images/2/2d/Shattering_Justice.png/revision/latest?cb=20190917165638",
    shortDescription: "Reduce the armor of enemies after repeatedly striking them.",
    description: "After hitting an enemy 5 times, reduce their armor by 60 for 8 (+8 per stack) seconds.",
    rarity: constant.ItemRarity.LEGENDARY,
    category: [
      constant.Category.DAMAGE,
    ],
    id: 85,
    stats: [{
      stat: constant.StatType.DURATION,
      value: "8s",
      stackType: constant.StackType.LINEAR,
      stackValue: "+8s", 
    }],
  },
  86: {
    wikiLink: "https://riskofrain2.fandom.com/wiki/Lepton_Daisy",
    name: "Lepton Daisy",
    image: "https://vignette.wikia.nocookie.net/riskofrain2/images/7/73/Lepton_Daisy.png/revision/latest?cb=20190917165638",
    shortDescription: "Periodically release a healing nova during the Teleporter event.",
    description: "Release a healing nova during the Teleporter event, healing all nearby allies for 50% of their maximum health. Occurs 1 (+1 per stack) times.",
    rarity: constant.ItemRarity.UNCOMMON,
    category: [
      constant.Category.HEALING,
      constant.Category.AI_BLACKLIST,
    ],
    id: 86,
    stats: [{
      stat: constant.StatType.AMOUNT,
      value: "1",
      stackType: constant.StackType.LINEAR,
      stackValue: "+1", 
    }],
  },
  87: {
    wikiLink: "https://riskofrain2.fandom.com/wiki/Focus_Crystal",
    name: "Focus Crystal",
    image: "https://vignette.wikia.nocookie.net/riskofrain2/images/5/59/Focus_Crystal.png/revision/latest?cb=20190917165638",
    shortDescription: "Deal bonus damage to nearby enemies.",
    description: "Increase damage to enemies within 13m by 15% (+15% per stack).",
    rarity: constant.ItemRarity.COMMON,
    category: [
      constant.Category.DAMAGE,
    ],
    id: 87,
    stats: [{
      stat: constant.StatType.DAMAGE,
      value: "15%",
      stackType: constant.StackType.LINEAR,
      stackValue: "+15%", 
    }],
  },
  88: {
    wikiLink: "https://riskofrain2.fandom.com/wiki/Strides_of_Heresy",
    name: "Strides of Heresy",
    image: "https://vignette.wikia.nocookie.net/riskofrain2/images/1/1a/Strides_of_Heresy.png/revision/latest?cb=20190917165638",
    shortDescription: "Replace your Utility Skill with 'Shadowfade'.",
    description: "Replace your Utility Skill with Shadowfade.\n\nFade away, becoming intangible and gaining +30% movement speed. Heal for 25% (+25% per stack) of your maximum health. Lasts 3 (+3 per stack) seconds.",
    rarity: constant.ItemRarity.LUNAR,
    category: [
      constant.Category.UTILITY,
      constant.Category.HEALING,
    ],
    id: 88,
    stats: [{
      stat: constant.StatType.HEAL,
      value: "25%",
      stackType: constant.StackType.LINEAR,
      stackValue: "+25%",
      effectiveMax: 4, 
    },
    {
      stat: constant.StatType.DURATION,
      value: "3s",
      stackType: constant.StackType.LINEAR,
      stackValue: "+3s", 
    }],
  },
  90: {
    wikiLink: "https://riskofrain2.fandom.com/wiki/Razorwire",
    name: "Razorwire",
    image: "https://vignette.wikia.nocookie.net/riskofrain2/images/a/ac/Razorwire.png/revision/latest?cb=20191217214157",
    shortDescription: "Retaliate in a burst of razors on taking damage.",
    description: "Getting hit causes you to explode in a burst of razors, dealing 160% damage. Hits up to 5 (+2 per stack) targets in a 25m (+10m per stack) radius.",
    rarity: constant.ItemRarity.UNCOMMON,
    category: [
      constant.Category.DAMAGE,
      constant.Category.AI_BLACKLIST,
    ],
    id: 90,
    stats: [{
      stat: constant.StatType.AMOUNT,
      value: "5",
      stackType: constant.StackType.LINEAR,
      stackValue: "+2",
      effectiveMax: 21, 
    },
    {
      stat: constant.StatType.RADIUS,
      value: "25m",
      stackType: constant.StackType.LINEAR,
      stackValue: "+10m", 
    }],
  },
  91: {
    wikiLink: "https://riskofrain2.fandom.com/wiki/Fresh_Meat",
    name: "Fresh Meat",
    image: "https://vignette.wikia.nocookie.net/riskofrain2/images/e/ec/Fresh_Meat.png/revision/latest?cb=20191217215200",
    shortDescription: "Regenerate health after killing an enemy.",
    description: "Increases base health regeneration by +2 hp/s for 3s (+3s per stack) after killing an enemy.",
    rarity: constant.ItemRarity.COMMON,
    category: [
      constant.Category.HEALING,
      constant.Category.ON_KILL_EFFECT,
    ],
    id: 91,
    stats: [{
      stat: constant.StatType.DURATION,
      value: "3s",
      stackType: constant.StackType.LINEAR,
      stackValue: "+3s", 
    }],
  },
  92: {
    wikiLink: "https://riskofrain2.fandom.com/wiki/Pearl",
    name: "Pearl",
    image: "https://vignette.wikia.nocookie.net/riskofrain2/images/7/73/Pearl.png/revision/latest?cb=20191217214156",
    shortDescription: "Increase your maximum health.",
    description: "Increases maximum health by 10% (+10% per stack).",
    rarity: constant.ItemRarity.BOSS,
    dropsFrom: "Cleansing Pool",
    category: [
      constant.Category.UTILITY,
      constant.Category.WORLD_UNIQUE,
    ],
    id: 92,
    stats: [{
      stat: constant.StatType.TOTAL_HEALTH,
      value: "10%",
      stackType: constant.StackType.LINEAR,
      stackValue: "+10%", 
    }],
  },
  93: {
    wikiLink: "https://riskofrain2.fandom.com/wiki/Irradiant_Pearl",
    name: "Irradiant Pearl",
    image: "https://vignette.wikia.nocookie.net/riskofrain2/images/e/ef/Irradiant_Pearl.png/revision/latest?cb=20191217214156",
    shortDescription: "Increase ALL of your stats.",
    description: "Increases ALL stats by 10% (+10% per stack).",
    rarity: constant.ItemRarity.BOSS,
    dropsFrom: "Cleansing Pool",
    category: [
      constant.Category.DAMAGE,
      constant.Category.HEALING,
      constant.Category.UTILITY,
      constant.Category.WORLD_UNIQUE,
    ],
    id: 93,
    stats: [{
      stat: constant.StatType.TOTAL_HEALTH,
      value: "10%",
      stackType: constant.StackType.LINEAR,
      stackValue: "+10%", 
    },
    {
      stat: constant.StatType.HEALTH_REGENERATION,
      value: "10%",
      stackType: constant.StackType.LINEAR,
      stackValue: "+10%", 
    },
    {
      stat: constant.StatType.MOVEMENT_SPEED,
      value: "10%",
      stackType: constant.StackType.LINEAR,
      stackValue: "+10%", 
    },
    {
      stat: constant.StatType.DAMAGE,
      value: "10%",
      stackType: constant.StackType.LINEAR,
      stackValue: "+10%", 
    },
    {
      stat: constant.StatType.ATTACK_SPEED,
      value: "10%",
      stackType: constant.StackType.LINEAR,
      stackValue: "+10%", 
    },
    {
      stat: constant.StatType.CRITICAL_STRIKE_CHANCE,
      value: "10%",
      stackType: constant.StackType.LINEAR,
      stackValue: "+10%", 
    },
    {
      stat: constant.StatType.ARMOUR,
      value: "10%",
      stackType: constant.StackType.LINEAR,
      stackValue: "+10%", 
    }],
  },
  94: {
    wikiLink: "https://riskofrain2.fandom.com/wiki/Ghor%27s_Tome",
    name: "Ghor's Tome",
    image: "https://vignette.wikia.nocookie.net/riskofrain2/images/9/9a/Ghor%27s_Tome.png/revision/latest?cb=20191217214156",
    shortDescription: "Chance on kill to drop a treasure.",
    description: "4% (+4% on stack) chance on kill to drop a treasure worth $25. Scales over time.",
    rarity: constant.ItemRarity.UNCOMMON,
    category: [
      constant.Category.UTILITY,
      constant.Category.ON_KILL_EFFECT,
    ],
    id: 94,
    stats: [{
      stat: constant.StatType.CHANCE,
      value: "4%",
      stackType: constant.StackType.LINEAR,
      stackValue: "+4%",
      effectiveMax: 25, 
    }],
  },
  95: {
    wikiLink: "https://riskofrain2.fandom.com/wiki/Resonance_Disc",
    name: "Resonance Disc",
    image: "https://vignette.wikia.nocookie.net/riskofrain2/images/8/8d/Resonance_Disc.png/revision/latest?cb=20191217215521",
    shortDescription: "Obtain a Resonance Disc charged by killing enemies. Fires automatically when fully charged.",
    description: "Killing enemies charges the Resonance Disc. The disc launches itself toward a target for 300% base damage (+300% per stack), piercing all enemies it doesn't kill, and then explodes for 1000% base damage (+1000% per stack). Returns to the user, striking all enemies along the way for 300% base damage (+300% per stack).",
    rarity: constant.ItemRarity.LEGENDARY,
    category: [
      constant.Category.DAMAGE,
      constant.Category.ON_KILL_EFFECT,
    ],
    id: 95,
    stats: [{
      stat: constant.StatType.DAMAGE,
      value: "300%",
      stackType: constant.StackType.LINEAR,
      stackValue: "+300%", 
    },
    {
      stat: constant.StatType.DAMAGE,
      value: "1000%",
      stackType: constant.StackType.LINEAR,
      stackValue: "+1000%", 
    }],
  },
  96: {
    wikiLink: "https://riskofrain2.fandom.com/wiki/Visions_of_Heresy",
    name: "Visions of Heresy",
    image: "https://vignette.wikia.nocookie.net/riskofrain2/images/3/31/Visions_of_Heresy.png/revision/latest?cb=20191217215521",
    shortDescription: "Replace your Primary Skill with 'Hungering Gaze'.",
    description: "Replace your Primary Skill with Hungering Gaze.\n\nFire a flurry of tracking shards that detonate after a delay, dealing 120% base damage. Hold up to 12 charges (+12 per stack) that reload after 2 seconds (+2 per stack).",
    rarity: constant.ItemRarity.LUNAR,
    category: [
      constant.Category.DAMAGE,
    ],
    id: 96,
    stats: [{
      stat: constant.StatType.CHARGE,
      value: "12",
      stackType: constant.StackType.LINEAR,
      stackValue: "+12", 
    },
    {
      stat: constant.StatType.COOLDOWN,
      value: "2s",
      stackType: constant.StackType.LINEAR,
      stackValue: "+2s", 
    }],
  },
  97: {
    wikiLink: "https://riskofrain2.fandom.com/wiki/Genesis_Loop",
    name: "Genesis Loop",
    image: "https://vignette.wikia.nocookie.net/riskofrain2/images/c/c8/Genesis_Loop.png/revision/latest?cb=20191217215521",
    shortDescription: "Fire an electric nova at low health.",
    description: "Falling below 25% health causes you to explode, dealing 6000% base damage. Recharges every 30 seconds (-50% per stack).",
    rarity: constant.ItemRarity.BOSS,
    dropsFrom: "Wandering Vagrant",
    category: [
      constant.Category.DAMAGE,
    ],
    id: 97,
    stats: [{
      stat: constant.StatType.COOLDOWN,
      value: "30s",
      stackType: constant.StackType.EXPONENTIAL,
      stackValue: "-50%",
      effectiveMax: 11, 
    }],
  },
  98: {
    wikiLink: "https://riskofrain2.fandom.com/wiki/Beads_of_Fealty",
    name: "Beads of Fealty",
    image: "https://vignette.wikia.nocookie.net/riskofrain2/images/0/07/Beads_of_Fealty.png/revision/latest?cb=20191217214156",
    shortDescription: "Seems to do nothing... but...",
    description: "Celestial Portals will take the player to A Moment, Whole instead of A Moment, Fractured.",
    rarity: constant.ItemRarity.LUNAR,
    category: [
      constant.Category.LUNAR,
    ],
    id: 98,
  },
};

const equipment = {
  0: {
    wikiLink: "https://riskofrain2.fandom.com/wiki/Disposable_Missile_Launcher",
    name: "Disposable Missile Launcher",
    image: "https://vignette.wikia.nocookie.net/riskofrain2/images/7/78/Disposable_Missile_Launcher.png/revision/latest?cb=20190411034416",
    shortDescription: "Fire a swarm of missiles.",
    description: "Fire a swarm of 12 missiles that deal 12x300% damage.",
    rarity: constant.ItemRarity.EQUIPMENT,
    category: [
      constant.Category.DAMAGE,
    ],
    id: 0,
    cooldown: "45s",
  },
  1: {
    wikiLink: "https://riskofrain2.fandom.com/wiki/Foreign_Fruit",
    name: "Foreign Fruit",
    image: "https://vignette.wikia.nocookie.net/riskofrain2/images/d/d0/Foreign_Fruit.png/revision/latest?cb=20190411034733",
    shortDescription: "Heal on use.",
    description: "Instantly heal for 50% of your maximum health.",
    rarity: constant.ItemRarity.EQUIPMENT,
    category: [
      constant.Category.HEALING,
    ],
    id: 1,
    cooldown: "45s",
  },
  2: {
    wikiLink: "https://riskofrain2.fandom.com/wiki/Glowing_Meteorite",
    name: "Glowing Meteorite",
    image: "https://vignette.wikia.nocookie.net/riskofrain2/images/f/f4/Glowing_Meteorite.png/revision/latest?cb=20190411034756",
    shortDescription: "Rain meteors from the sky, hurting both enemies and allies.",
    description: "Rain meteors from the sky, damaging ALL characters for 600% damage per blast. Lasts 20 seconds.",
    rarity: constant.ItemRarity.LUNAR_EQUIPMENT,
    category: [
      constant.Category.DAMAGE,
    ],
    id: 2,
    cooldown: "140s",
  },
  4: {
    wikiLink: "https://riskofrain2.fandom.com/wiki/Ifrit%27s_Distinction",
    name: "Ifrit's Distinction",
    image: "https://vignette.wikia.nocookie.net/riskofrain2/images/0/08/Ifrit%27s_Distinction.png/revision/latest?cb=20190411034831",
    shortDescription: "Become an aspect of fire.",
    description: "You become Blazing. A trail of fire will follow you. Enemies that you attack, or that make contact with your trail will be ignited for 4s dealing 100% damage.",
    dropsFrom: "Blazing Elites",
    rarity: constant.ItemRarity.ELITE_EQUIPMENT,
    category: [
      constant.Category.TRANSFORMATION,
    ],
    id: 4,
  },
  5: {
    wikiLink: "https://riskofrain2.fandom.com/wiki/Silence_Between_Two_Strikes",
    name: "Silence Between Two Strikes",
    image: "https://vignette.wikia.nocookie.net/riskofrain2/images/0/0a/Silence_Between_Two_Strikes.png/revision/latest?cb=20190411035058",
    shortDescription: "Become an aspect of lightning.",
    description: "You become Overloading. 50% of your health is replaced by sheilds that rapidly recharge 7 seconds after you've stopped taking damage. Attacks attach a bomb that explodes after 1.5s dealing 100% damage.",
    dropsFrom: "Overloading Elites",
    rarity: constant.ItemRarity.ELITE_EQUIPMENT,
    category: [
      constant.Category.TRANSFORMATION,
    ],
    id: 5,
  },
  8: {
    wikiLink: "https://riskofrain2.fandom.com/wiki/Her_Biting_Embrace",
    name: "Her Biting Embrace",
    image: "https://vignette.wikia.nocookie.net/riskofrain2/images/8/8b/Her_Biting_Embrace.png/revision/latest?cb=20190411034825",
    shortDescription: "Become an aspect of ice.",
    description: "You become Glacial. Attacked enemies are slowed for 80% on hit for 1.5s. When a player holding this equipment dies, after 2s they will explode for 150% damage in addition to freezing enemies around them.",
    dropsFrom: "Glacial Elites",
    rarity: constant.ItemRarity.ELITE_EQUIPMENT,
    category: [
      constant.Category.TRANSFORMATION,
    ],
    id: 8,
  },
  9: {
    wikiLink: "https://riskofrain2.fandom.com/wiki/N%27kuhana%27s_Retort",
    name: "N'kuhana's Retort",
    image: "https://vignette.wikia.nocookie.net/riskofrain2/images/9/9b/N%27kuhana%27s_Retort.png/revision/latest?cb=20190625201107",
    shortDescription: "Become an aspect of corruption.",
    description: "You become Malachite. You periodically release 3-4 spiked balls that sprout spike pits when they land. On death you have a chance to spawn a Malachite Urchin that shoots spikes until it expires.",
    dropsFrom: "Malachite Elites",
    rarity: constant.ItemRarity.ELITE_EQUIPMENT,
    category: [
      constant.Category.TRANSFORMATION,
    ],
    id: 9,
  },
  10: {
    wikiLink: "https://riskofrain2.fandom.com/wiki/Primordial_Cube",
    name: "Primordial Cube",
    image: "https://vignette.wikia.nocookie.net/riskofrain2/images/d/d9/Primordial_Cube.png/revision/latest?cb=20190411034952",
    shortDescription: "Fire a black hole that draws enemies in.",
    description: "Fire a black hole that draws enemies within 30m into its center. Lasts 10 seconds",
    rarity: constant.ItemRarity.EQUIPMENT,
    category: [
      constant.Category.UTILITY,
    ],
    id: 10,
    cooldown: "60s",
  },
  12: {
    wikiLink: "https://riskofrain2.fandom.com/wiki/Ocular_HUD",
    name: "Ocular HUD",
    image: "https://vignette.wikia.nocookie.net/riskofrain2/images/6/68/Ocular_HUD.png/revision/latest?cb=20190411034925",
    shortDescription: "Gain 100% Critical Strike Chance for 8 seconds.",
    description: "Gain +100% Critical Strike Chance for 8 seconds.",
    rarity: constant.ItemRarity.EQUIPMENT,
    category: [
      constant.Category.DAMAGE,
    ],
    id: 12,
    cooldown: "60s",
  },
  13: {
    wikiLink: "https://riskofrain2.fandom.com/wiki/The_Back-up",
    name: "The Back-up",
    image: "https://vignette.wikia.nocookie.net/riskofrain2/images/3/39/The_Back-up.png/revision/latest?cb=20190411035118",
    shortDescription: "Call drones for back up. Lasts 25 seconds.",
    description: "Call 4 Strike Drones to fight for you. Lasts 25 seconds.",
    rarity: constant.ItemRarity.EQUIPMENT,
    category: [
      constant.Category.DAMAGE,
    ],
    unlock: {
      name: "Mechanic",
      description: "The achievement is obtained by repairing 30 drones or turrets.",
      link: "https://riskofrain2.fandom.com/wiki/Mechanic",
    },
    id: 13,
    cooldown: "100s",
  },
  15: {
    wikiLink: "https://riskofrain2.fandom.com/wiki/Preon_Accumulator",
    name: "Preon Accumulator",
    image: "https://vignette.wikia.nocookie.net/riskofrain2/images/f/fe/Preon_Accumulator.png/revision/latest?cb=20190411034948",
    shortDescription: "Fire a ball of energy that electrocutes nearby enemies before detonating.",
    description: "Fires preon tendrils, zapping enemies within 35m for up to 600% damage/second. On contact, detonate in an enormous 20m explosion for 4000% damage.",
    rarity: constant.ItemRarity.EQUIPMENT,
    category: [
      constant.Category.DAMAGE,
    ],
    unlock: {
      name: "[REDACTED]",
      description: "The achievement is obtained by opening the Timed Security Chest on Rallypoint Delta.",
      link: "https://riskofrain2.fandom.com/wiki/REDACTED",
    },
    id: 15,
    cooldown: "140s",
  },
  17: {
    wikiLink: "https://riskofrain2.fandom.com/wiki/Milky_Chrysalis",
    name: "Milky Chrysalis",
    image: "https://vignette.wikia.nocookie.net/riskofrain2/images/e/e3/Milky_Chrysalis.png/revision/latest?cb=20190411034912",
    shortDescription: "Gain temporary flight.",
    description: "Sprout wings and fly for 15 seconds. Gain +20% movement speed for the duration.",
    rarity: constant.ItemRarity.EQUIPMENT,
    category: [
      constant.Category.UTILITY,
    ],
    id: 17,
    cooldown: "60s",
  },
  18: {
    wikiLink: "https://riskofrain2.fandom.com/wiki/Royal_Capacitor",
    name: "Royal Capacitor",
    image: "https://vignette.wikia.nocookie.net/riskofrain2/images/e/ef/Royal_Capacitor.png/revision/latest?cb=20190411035019",
    shortDescription: "Call down a lightning strike on a targeted monster.",
    description: "Call down a lightning strike on a targeted monster, dealing 3000% damage and stunning nearby monsters.",
    rarity: constant.ItemRarity.EQUIPMENT,
    category: [
      constant.Category.DAMAGE,
    ],
    unlock: {
      name: "Ascendant",
      description: "The achievement is obtained by defeating the Teleporter bosses after activating 2 Shrines of the Mountain.",
      link: "https://riskofrain2.fandom.com/wiki/Ascendant",
    },
    id: 18,
    cooldown: "20s",
  },
  19: {
    wikiLink: "https://riskofrain2.fandom.com/wiki/The_Crowdfunder",
    name: "The Crowdfunder",
    image: "https://vignette.wikia.nocookie.net/riskofrain2/images/d/d4/The_Crowdfunder.png/revision/latest?cb=20190411035123",
    shortDescription: "Toggle to fire. Costs gold per bullet.",
    description: "Fires a continuous barrage that deals 100% damage per bullet. Costs $1 per bullet. Cost increases over time.",
    rarity: constant.ItemRarity.EQUIPMENT,
    category: [
      constant.Category.DAMAGE,
    ],
    unlock: {
      name: "Funded!",
      description: "The achievement is obtained by collecting $30,480 total gold.",
      link: "https://riskofrain2.fandom.com/wiki/Funded!",
    },
    id: 19,
  },
  20: {
    wikiLink: "https://riskofrain2.fandom.com/wiki/Gnarled_Woodsprite",
    name: "Gnarled Woodsprite",
    image: "https://vignette.wikia.nocookie.net/riskofrain2/images/d/d8/Gnarled_Woodsprite.png/revision/latest?cb=20190411034800",
    shortDescription: "Heal over time. Activate to send to an ally.",
    description: "Gain a Woodsprite follower that heals for 1.5% of your maximum health/second. Can be sent to an ally to heal them for 10% of their maximum health.",
    rarity: constant.ItemRarity.EQUIPMENT,
    category: [
      constant.Category.HEALING,
    ],
    unlock: {
      name: "One with the Woods",
      description: "The achievement is obtained by fully upgrading a Shrine of the Woods.",
      link: "https://riskofrain2.fandom.com/wiki/One_with_the_Woods",
    },
    id: 20,
    cooldown: "15s",
  },
  22: {
    wikiLink: "https://riskofrain2.fandom.com/wiki/Helfire_Tincture",
    name: "Helfire Tincture",
    image: "https://vignette.wikia.nocookie.net/riskofrain2/images/4/4d/Helfire_Tincture.png/revision/latest?cb=20190411034821",
    shortDescription: "Burn everything nearby... including you and allies.",
    description: "Ignite ALL characters within 8m. Deal 5% of your maximum health/second as burning to yourself. The burn is 0.5x stronger on allies, and 24x stronger on enemies.",
    rarity: constant.ItemRarity.LUNAR_EQUIPMENT,
    category: [
      constant.Category.DAMAGE,
    ],
    id: 22,
    cooldown: "45s",
  },
  24: {
    wikiLink: "https://riskofrain2.fandom.com/wiki/Radar_Scanner",
    name: "Radar Scanner",
    image: "https://vignette.wikia.nocookie.net/riskofrain2/images/7/7f/Radar_Scanner.png/revision/latest?cb=20190411035002",
    shortDescription: "Reveal all nearby interactables.",
    description: "Reveal all interactables within 500m for 10 seconds.",
    rarity: constant.ItemRarity.EQUIPMENT,
    category: [
      constant.Category.UTILITY,
    ],
    unlock: {
      name: "Bookworm",
      description: "The achievement is obtained by collecting 10 Monster or Environment Logs.",
      link: "https://riskofrain2.fandom.com/wiki/Bookworm",
    },
    id: 24,
    cooldown: "45s",
  },
  25: {
    wikiLink: "https://riskofrain2.fandom.com/wiki/Effigy_of_Grief",
    name: "Effigy of Grief",
    image: "https://vignette.wikia.nocookie.net/riskofrain2/images/4/45/Effigy_of_Grief.png/revision/latest?cb=20190411034724",
    shortDescription: "Drop an effigy that cripples ALL characters inside. Can be picked back up.",
    description: "ALL characters within are slowed by 50% and have their armor reduced by 20.",
    rarity: constant.ItemRarity.LUNAR_EQUIPMENT,
    category: [
      constant.Category.UTILITY,
    ],
    id: 25,
  },
  26: {
    wikiLink: "https://riskofrain2.fandom.com/wiki/Eccentric_Vase",
    name: "Eccentric Vase",
    image: "https://vignette.wikia.nocookie.net/riskofrain2/images/c/ce/Eccentric_Vase.png/revision/latest?cb=20190625193715",
    shortDescription: "Create a quantum tunnel between two locations.",
    description: "Create a quantum tunnel of up to 1000m in length. Lasts 30 seconds.",
    rarity: constant.ItemRarity.EQUIPMENT,
    category: [
      constant.Category.UTILITY,
    ],
    id: 26,
    cooldown: "45s",
  },
  27: {
    wikiLink: "https://riskofrain2.fandom.com/wiki/Spinel_Tonic",
    name: "Spinel Tonic",
    image: "https://vignette.wikia.nocookie.net/riskofrain2/images/2/29/Spinel_Tonic.png/revision/latest?cb=20190625193715",
    shortDescription: "Gain a massive boost to ALL stats. Chance to gain an affliction that reduces ALL stats.",
    description: "Drink the Tonic, gaining a boost for 20 seconds. Increases damage by +100%. Increases attack speed by +70%. Increases armor by +20. Increases maximum health by +50%. Increases passive health regeneration by +300%. Increases movespeed by +30%.\n\nWhen the Tonic wears off, you have a 20% chance to gain a Tonic Affliction, reducing all of your stats by -5% (-5% per stack).",
    rarity: constant.ItemRarity.LUNAR_EQUIPMENT,
    category: [
      constant.Category.DAMAGE,
      constant.Category.HEALING,
    ],
    id: 27,
    cooldown: "60s",
  },
  28: {
    wikiLink: "https://riskofrain2.fandom.com/wiki/Fuel_Array",
    name: "Fuel Array",
    image: "https://vignette.wikia.nocookie.net/riskofrain2/images/f/fe/Fuel_Array.png/revision/latest?cb=20190625193715",
    shortDescription: "Looks like it could power something. EXTREMELY unstable...",
    description: "Can be used to unlock Rex in the Abyssal Depths stage. Falling below 50% health will force the array to explode dealing 300% of play health as damage.",
    rarity: constant.ItemRarity.EQUIPMENT,
    category: [
      constant.Category.MISC,
    ],
    id: 28,
  },
  29: {
    wikiLink: "https://riskofrain2.fandom.com/wiki/Blast_Shower",
    name: "Blast Shower",
    image: "https://vignette.wikia.nocookie.net/riskofrain2/images/4/4f/Blast_Shower.png/revision/latest?cb=20190917165637",
    shortDescription: "Cleanse all negative effects.",
    description: "Cleanse all negative effects. Includes debuffs, damage over time, and nearby projectiles.",
    rarity: constant.ItemRarity.EQUIPMENT,
    category: [
      constant.Category.UTILITY,
    ],
    id: 29,
    cooldown: "20s",
  },
  30: {
    wikiLink: "https://riskofrain2.fandom.com/wiki/Volcanic_Egg",
    name: "Volcanic Egg",
    image: "https://vignette.wikia.nocookie.net/riskofrain2/images/2/2e/Volcanic_Egg.png/revision/latest?cb=20190917165638",
    shortDescription: "Transform into a speeding draconic fireball, dealing damage as you pass through enemies.",
    description: "Turn into a draconic fireball for 5 seconds. Deal 500% damage on impact. Detonates at the end for 800% damage.",
    rarity: constant.ItemRarity.EQUIPMENT,
    category: [
      constant.Category.DAMAGE,
    ],
    id: 30,
    cooldown: "30s",
  },
  31: {
    wikiLink: "https://riskofrain2.fandom.com/wiki/Spectral_Circlet",
    name: "Spectral Circlet",
    image: "https://vignette.wikia.nocookie.net/riskofrain2/images/d/d2/Spectral_Circlet.png/revision/latest?cb=20191118080840",
    shortDescription: "Become an aspect of incorporeality.",
    description: "You become Celestine. Your attacks apply an 80% slow for 3 seconds.",
    dropsFrom: "Celestine Elites",
    rarity: constant.ItemRarity.ELITE_EQUIPMENT,
    category: [
      constant.Category.TRANSFORMATION,
    ],
    id: 31,
  },
  32: {
    wikiLink: "https://riskofrain2.fandom.com/wiki/Jade_Elephant",
    name: "Jade Elephant",
    image: "https://vignette.wikia.nocookie.net/riskofrain2/images/4/41/Jade_Elephant.png/revision/latest?cb=20191217214157",
    shortDescription: "Gain massive armor for 5 seconds.",
    description: "Gain 500 armor for 5 seconds.",
    rarity: constant.ItemRarity.EQUIPMENT,
    category: [
      constant.Category.UTILITY,
    ],
    id: 32,
    cooldown: "45s",
  },
  33: {
    wikiLink: "https://riskofrain2.gamepedia.com/Sawmerang",
    name: "Sawmerang",
    image: "https://gamepedia.cursecdn.com/riskofrain2_gamepedia_en/6/62/Sawmerang.png?version=785219b11f53fbe9fd0e07dd1abe9aa3",
    shortDescription: "Throw a fan of buzzing saws that come back to you.",
    description: "Throw three large saw blades that slice through enemies for 3x400% damage. Also deals an additional 3x100% damage per second while bleeding enemies. Can strike enemies again on the way back.",
    rarity: constant.ItemRarity.EQUIPMENT,
    category: [
      constant.Category.DAMAGE,
    ],
    id: 33,
    cooldown: "45s",
  },
  34: {
    wikiLink: "https://riskofrain2.gamepedia.com/Recycler",
    name: "Recycler",
    image: "https://gamepedia.cursecdn.com/riskofrain2_gamepedia_en/6/67/Recycler.png?version=b3136dfd6d920dfd7b7b51854bd4ef5c",
    shortDescription: "Transform an Item or Equipment into a different one. Can only recycle once.",
    description: "Transform an Item or Equipment into a different one. Can only be converted into the same tier one time.",
    rarity: constant.ItemRarity.EQUIPMENT,
    category: [
      constant.Category.UTILITY,
    ],
    unlock: {
      name: "Cleanup Duty",
      description: "The achievement is obtained by destroying 20 flying rocks in Sky Meadow.",
      link: "https://riskofrain2.gamepedia.com/Cleanup_Duty",
    },
    id: 34,
    cooldown: "45s",
  },
};

module.exports = {
  items,
  equipment,
};
